# Generated by Django 5.1.7 on 2025-04-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_identifier', models.CharField(db_index=True, help_text='Original filename or URL', max_length=1024, unique=True)),
                ('title', models.CharField(default='Untitled Video/Audio', help_text='Display title for the chat session', max_length=255)),
                ('original_transcript', models.TextField(blank=True, null=True)),
                ('youtube_video_details_json', models.TextField(blank=True, help_text='JSON list of {"title": ..., "url": ...} for related YT videos', null=True)),
                ('youtube_chunks_json', models.TextField(blank=True, help_text='JSON list of YouTube transcript chunks for RAG', null=True)),
                ('youtube_embeddings_blob', models.BinaryField(blank=True, help_text='Binary blob of NumPy embeddings array for YouTube chunks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.videocontext')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
